import {StyleSheet} from 'react-native';
import globalStyles from 'src/config/globalStyles';
import {fontRef, heightRef, widthRef} from 'src/config/screenSize';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'flex-start',
    backgroundColor: '#FFFFFF',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    height: 70 * heightRef,
    alignSelf: 'center',
    backgroundColor: '#F6FAFB',
  },
  headerInner: {flexDirection: 'row', alignSelf: 'flex-start'},
  headerText: {
    marginLeft: 20 * widthRef,
    fontSize: 24 * heightRef,
    fontWeight: '600',
    color: 'black',
  },
  heading: {
    fontSize: 28,
    fontWeight: '600',
    color: '#454238',
    marginLeft: '5%',
    marginTop: 20,
    alignSelf: 'flex-start',
  },
  heading2: {
    fontSize: 16,
    fontWeight: '500',
    color: '#9BAAAF',
    marginLeft: '5%',
    marginTop: 5,
    alignSelf: 'flex-start',
  },
  searchView: {
    width: '93%',
    height: 50,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'flex-start',
    flexDirection: 'row',
    elevation: 10,
    shadowColor: 'gray',
    shadowOffset: {width: 0, height: 1},
    shadowOpacity: 0.1,
    marginTop: 10,
  },
  inputFeild: {
    width: '90%',
    marginLeft: 10,
    marginBottom: 10,
  },
  listView: {
    margin: 5,
    width: 370 * widthRef,
    maxHeight: 205 * heightRef,
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    justifyContent: 'space-between',
    alignItems: 'center',

    shadowColor: 'gray',
    shadowOffset: {width: 0, height: 0},
    shadowOpacity: 0.2,
    elevation: 5,
  },
  flatlistContainerStyle: {
    alignItems: 'center',
    marginBottom: 20,
  },
  msgView: {
    height: 25,
    width: 25,
    backgroundColor: globalStyles.Theme.primary,
    borderRadius: 12.5,
    alignItems: 'center',
    justifyContent: 'center',
    margin: 10,
  },
  msgText: {
    color: '#757B80',
    fontWeight: '500',
    fontSize: 16 * fontRef,
    marginTop: 5,
    marginLeft: 5,
  },
  countView: {height: '100%', width: '15%'},
  msgbox: {height: '100%', width: '85%'},
  bottomView: {
    // backgroundColor: 'blue',
    width: '95%',
    // height: 105,
    flexDirection: 'row',
    paddingBottom: 20 * heightRef,
  },
  timeText: {
    color: '#B3B5C2',
    fontWeight: '500',
    fontSize: 12,
    marginTop: 5,
    alignSelf: 'flex-end',
    marginRight: 5,
  },
  name: {
    color: '#454238',
    fontWeight: '500',
    fontSize: 16,
    marginTop: 3,
  },
  AvailabilityView: {
    height: 20,
    width: 20,
    backgroundColor: 'white',
    position: 'absolute',
    borderRadius: 10,
    bottom: 0,
    right: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },
  AvailabilityInnerView: {
    height: 13,
    width: 13,
    borderRadius: 10,
  },
  status: {fontWeight: '500', fontSize: 12, marginTop: 3},
  imgView: {height: 50, width: 50, borderRadius: 25, borderWidth:1,
    borderColor:globalStyles.Theme.primary,
  borderRadius:25,},
  topView: {
    height: 50,
    width: 50,
 
    
    marginLeft: 30,
  },
  main: {
    marginTop: 25,
    height: 50,
    width: '100%',
    // backgroundColor: 'yellow',
    flexDirection: 'row',
  },
  addView: {
    width: 200,
    height: 66 * heightRef,
    position: 'absolute',
    bottom: 60,
    right: 30,
  },
  addView2: {
    height: '100%',
    width: '100%',
    backgroundColor: globalStyles.Theme.primary,
    alignSelf: 'center',
    borderRadius: 40,
    justifyContent: 'center',
  },
  addText: {
    marginLeft: 15,
    fontSize: 16,
    fontWeight: '500',
    color: '#FFFFFF',
  },
  addButton: {
    position: 'absolute',
  top: 15*heightRef,
    right: 10,
    shadowColor: 'black',
    shadowOffset: {width: 0, height: 0},
    shadowOpacity: 0.4,
    elevation: 10,
  },
});

export default styles;
